apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: devops-automation
spec:
  selector:
    matchLabels:
      app: devops-automation
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: devops-automation
    spec:
      containers: 
        - name: devops-automation
          image: ajaykamble10/devops-automation # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # The port that the container is running on in the cluster

---

apiVersion: v1 #Kubernetes API version
kind: Service #Kubernetes resource kind we creating
metadata:   #Metadat of the resource kind we creating
    name: devops-automation
spec: 
    selector: 
      app: devops-automation
    ports: 
      - protocol: "TCP"
        port: 8080 #The port that the service is running on in the cluster
        targetedPort: 8080 #The port exposed by the service
    type: NodePort  #type of the service  